services:
  mysql:
    image: mysql:8.0
    container_name: ocache_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ocache
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
